brew "rcm"

# Shell & tools
brew "bash"
brew "bash-completion"
brew "fzf"
brew "git"
brew "gnupg"
brew "pinentry-mac"
brew "ripgrep"
brew "tree"
brew "xh"

# Fonts
tap "homebrew/cask-fonts"
cask "font-iosevka-ss15"

# Project-specific
brew "awscli"
brew "aws-vault"
