window:
  dynamic_title: true
  padding:
    x: 5
    y: 5
  decorations_theme_variant: Dark
  option_as_alt: Both

cursor:
  style:
    shape: Block
    blinking: On
  unfocused_hollow: true

font:
  normal:
    family: "PragmataPro"
  size: 14

hints:
  enabled:
    - regex: "(magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
      command: open
      post_processing: true
      mouse:
        enabled: true
        mods: Command
      binding:
        key: U
        mods: Command|Shift

key_bindings:
  - { key: K, mods: Command, action: ClearHistory }

# github Alacritty Colors
# https://github.com/projekt0n/github-theme-contrib/blob/main/alacritty/github_dark.yml
colors:
  primary:
    background: "0x24292e"
    foreground: "0xd1d5da"
    bright_foreground: "0xfafbfc"
  normal:
    black: "0x586069"
    red: "0xea4a5a"
    green: "0x34d058"
    yellow: "0xffea7f"
    blue: "0x2188ff"
    magenta: "0xb392f0"
    cyan: "0x39c5cf"
    white: "0xd1d5da"
  bright:
    black: "0x959da5"
    red: "0xf97583"
    green: "0x85e89d"
    yellow: "0xffea7f"
    blue: "0x79b8ff"
    magenta: "0xb392f0"
    cyan: "0x56d4dd"
    white: "0xfafbfc"
  indexed_colors:
    - { index: 16, color: "0xd18616" }
    - { index: 17, color: "0xf97583" }

draw_bold_text_with_bright_colors: true
