#!/bin/bash

# Layout govuk_docker: Set up for projects run through GOV.UK
layout_govuk_docker_app() {
  local project_name=$(basename $(pwd))
  export GOVUK_PROJECT_NAME=$project_name

  # Set up GOV.UK Docker
  export GOVUK_ROOT_DIR=$HOME/Developer/govuk
  PATH_add "$GOVUK_ROOT_DIR/govuk-docker/exe"
}
